ALTER TABLE public.partners
  ALTER COLUMN code TYPE VARCHAR(20) USING code::VARCHAR,
  ALTER COLUMN name TYPE VARCHAR(200) USING name::VARCHAR,
  ALTER COLUMN email TYPE VARCHAR(255) USING email::VARCHAR,
  ALTER COLUMN phone TYPE VARCHAR(30) USING phone::VARCHAR,
  ALTER COLUMN address TYPE TEXT USING address::TEXT,
  ALTER COLUMN tax_number TYPE VARCHAR(100) USING tax_number::VARCHAR,
  ALTER COLUMN currency TYPE VARCHAR(10) USING currency::VARCHAR;
