-- V14: Add Flutter cafe fields to partners table
ALTER TABLE partners ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE partners ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE partners ADD COLUMN IF NOT EXISTS is_open BOOLEAN DEFAULT true;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS price DOUBLE PRECISION DEFAULT 0.0;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS likes INTEGER DEFAULT 0;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS active_players INTEGER DEFAULT 0;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS quiz_status VARCHAR(50);
ALTER TABLE partners ADD COLUMN IF NOT EXISTS has_active_quiz BOOLEAN DEFAULT false;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS is_trending BOOLEAN DEFAULT false;
ALTER TABLE partners ADD COLUMN IF NOT EXISTS reviews INTEGER DEFAULT 0;
